name: Deploy web to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-first-server:
    runs-on: runner-1  # Esto asume que tienes un runner configurado en el mismo servidor

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy into web
      run: |
        echo "stoping website"
        sudo /usr/local/bin/pm2 delete 0
        ls
        sudo cp -r ./ /var/www/curemd.io/website/CureMDplus/
        cd /var/www/curemd.io/website/CureMDplus/
        echo "running build"
        sudo npm  install
        sudo npm run build 
        sudo /usr/local/bin/pm2 start --name "myapp" --user "apache" --uid 48 --cwd /var/www/curemd.io/website/CureMDplus/ npm -- run dev
        sudo /usr/local/bin/pm2 save
        echo "deploy server 1 done"
        echo "starting second deploy"
        

  deploy-second:
    runs-on: runner-2  # Esto asume que tienes un runner configurado en el mismo servidor

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy into web
      run: |
        echo "stoping website"
        sudo /usr/local/bin/pm2 delete 0
        ls
        sudo cp -r ./ /var/www/curemd.io/website/CureMDplus/
        cd /var/www/curemd.io/website/CureMDplus/
        echo "running build"
        sudo npm  install
        sudo npm run build 
        sudo /usr/local/bin/pm2 start --name "myapp" --user "apache" --uid 48 --cwd /var/www/curemd.io/website/CureMDplus/ npm -- run dev
        sudo /usr/local/bin/pm2 save
        echo "deploy server 1 done"
        echo "starting second deploy"
        
        
