name: Deploy web to Dev

on:
  push:
    branches:
      - jorge-build-test

jobs:
  deploy:
    runs-on: self-hosted  # Esto asume que tienes un runner configurado en el mismo servidor

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy into web
      run: |
        echo "stoping website"
        sudo /usr/local/bin/pm2 stop 0
        ls
        sudo cp -r ./ /var/www/curemd.io/website/CureMDplus/
        cd /var/www/curemd.io/website/CureMDplus/
        echo "running build"
        sudo npm  install
        sudo npm run build 
        sudo /usr/local/bin/pm2 start 0
        echo "deploy server 1 done"
        echo "starting second deploy"
        scp -i "secret-key.pem" -r . ec2-user@3.220.189.206:/home/ec2-user/deploy-web
        ssh -i "secret-key.pem" ec2-user@3.220.189.206 
        cd /home/ec2-user/deploy-web 
        sudo cp -r /home/ec2-user/deploy-web/ /var/www/curemd.io/website/CureMDplus/
        echo "running build"
        sudo npm  install
        sudo npm run build 
        sudo /usr/local/bin/pm2 start 0
        echo "deploy server 2 done"
        